/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.theunknowname06.hilling;

/**
 *
 * @author Lutfi Hakim
 */
public class menuKalkulator extends javax.swing.JFrame {
    private String tPass;
    private String tEmail;
    private String tName;
    String angka;
    double jumlah, bilangan1, bilangan2;
    int pilih;
    /**
     * Creates new form menuKalkulator
     */
    public menuKalkulator(String n,String p,String e) {
        this.tPass = p;
        this.tName = n;
        this.tEmail = e;
        initComponents();
        angka = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tampilHasil = new javax.swing.JTextField();
        tClear = new javax.swing.JButton();
        tBagi = new javax.swing.JButton();
        tKali = new javax.swing.JButton();
        tSembbilan = new javax.swing.JButton();
        tDelapan = new javax.swing.JButton();
        tTujuh = new javax.swing.JButton();
        tEnam = new javax.swing.JButton();
        tEmpat = new javax.swing.JButton();
        tKurang = new javax.swing.JButton();
        tLima = new javax.swing.JButton();
        tTambah = new javax.swing.JButton();
        tTiga = new javax.swing.JButton();
        tSatu = new javax.swing.JButton();
        tDua = new javax.swing.JButton();
        tNol = new javax.swing.JButton();
        tTitik = new javax.swing.JButton();
        tHasil = new javax.swing.JButton();
        tKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        tampilHasil.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tampilHasil.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        tClear.setText("C");
        tClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tClearActionPerformed(evt);
            }
        });

        tBagi.setText("/");
        tBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBagiActionPerformed(evt);
            }
        });

        tKali.setText("X");
        tKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKaliActionPerformed(evt);
            }
        });

        tSembbilan.setText("9");
        tSembbilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSembbilanActionPerformed(evt);
            }
        });

        tDelapan.setText("8");
        tDelapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDelapanActionPerformed(evt);
            }
        });

        tTujuh.setText("7");
        tTujuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTujuhActionPerformed(evt);
            }
        });

        tEnam.setText("6");
        tEnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEnamActionPerformed(evt);
            }
        });

        tEmpat.setText("4");
        tEmpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmpatActionPerformed(evt);
            }
        });

        tKurang.setText("-");
        tKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKurangActionPerformed(evt);
            }
        });

        tLima.setText("5");
        tLima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLimaActionPerformed(evt);
            }
        });

        tTambah.setText("+");
        tTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTambahActionPerformed(evt);
            }
        });

        tTiga.setText("3");
        tTiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTigaActionPerformed(evt);
            }
        });

        tSatu.setText("1");
        tSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSatuActionPerformed(evt);
            }
        });

        tDua.setText("2");
        tDua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDuaActionPerformed(evt);
            }
        });

        tNol.setText("0");
        tNol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNolActionPerformed(evt);
            }
        });

        tTitik.setText(".");
        tTitik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTitikActionPerformed(evt);
            }
        });

        tHasil.setText("=");
        tHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tHasilActionPerformed(evt);
            }
        });

        tKembali.setText("Kembali ke Menu");
        tKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tampilHasil)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(tLima, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(tEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(tSembbilan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tKali, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tNol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tDua, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(tBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampilHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tBagi, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tClear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDelapan, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKali, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTujuh, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSembbilan, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLima, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEmpat, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEnam, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tDua, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSatu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTiga, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNol, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTitik, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSatuActionPerformed
        // TODO add your handling code here:
        angka += "1";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tSatuActionPerformed

    private void tTigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTigaActionPerformed
        // TODO add your handling code here:
        angka += "3";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tTigaActionPerformed

    private void tTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTambahActionPerformed
        // TODO add your handling code here:
        bilangan1 = Double.parseDouble(angka);
        tampilHasil.setText("+");
        angka = "";
        pilih = 4;
    }//GEN-LAST:event_tTambahActionPerformed

    private void tLimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLimaActionPerformed
        // TODO add your handling code here:
        angka += "5";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tLimaActionPerformed

    private void tKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKurangActionPerformed
        // TODO add your handling code here:
        bilangan1 = Double.parseDouble(angka);
        tampilHasil.setText("-");
        angka = "";
        pilih = 3;
    }//GEN-LAST:event_tKurangActionPerformed

    private void tEmpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmpatActionPerformed
        // TODO add your handling code here:
        angka += "4";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tEmpatActionPerformed

    private void tEnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEnamActionPerformed
        // TODO add your handling code here:
        angka += "6";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tEnamActionPerformed

    private void tTujuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTujuhActionPerformed
        // TODO add your handling code here:
        angka += "7";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tTujuhActionPerformed

    private void tDelapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDelapanActionPerformed
        // TODO add your handling code here:
        angka += "8";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tDelapanActionPerformed

    private void tSembbilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSembbilanActionPerformed
        // TODO add your handling code here:
        angka += "9";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tSembbilanActionPerformed

    private void tKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKaliActionPerformed
        // TODO add your handling code here:
        bilangan1 = Double.parseDouble(angka);
        tampilHasil.setText("X");
        angka = "";
        pilih = 2;
    }//GEN-LAST:event_tKaliActionPerformed

    private void tBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBagiActionPerformed
        // TODO add your handling code here:
        bilangan1 = Double.parseDouble(angka);
        tampilHasil.setText("/");
        angka = "";
        pilih = 1;
    }//GEN-LAST:event_tBagiActionPerformed

    private void tClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tClearActionPerformed
        // TODO add your handling code here:
        tampilHasil.setText(angka);
        bilangan1 = 0.0;
        bilangan2 = 0.0;
        jumlah = 0.0;
        angka = "";
    }//GEN-LAST:event_tClearActionPerformed

    private void tDuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDuaActionPerformed
        // TODO add your handling code here:
        angka += "2";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tDuaActionPerformed

    private void tNolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNolActionPerformed
        // TODO add your handling code here:
        angka += "0";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tNolActionPerformed

    private void tTitikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTitikActionPerformed
        // TODO add your handling code here:
        angka += ",";
        tampilHasil.setText(angka);
    }//GEN-LAST:event_tTitikActionPerformed

    private void tHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tHasilActionPerformed
        // TODO add your handling code here:
        switch(pilih){
            case 1:
                bilangan2 = Double.parseDouble(angka);
                jumlah = bilangan1 / bilangan2;
                angka = Double.toString(jumlah);
                tampilHasil.setText(angka);
                break;
            case 2:
                bilangan2 = Double.parseDouble(angka);
                jumlah = bilangan1 * bilangan2;
                angka = Double.toString(jumlah);
                tampilHasil.setText(angka);
                break;
            case 3:
                bilangan2 = Double.parseDouble(angka);
                jumlah = bilangan1 - bilangan2;
                angka = Double.toString(jumlah);
                tampilHasil.setText(angka);
                break;
            case 4:
                bilangan2 = Double.parseDouble(angka);
                jumlah = bilangan1 + bilangan2;
                angka = Double.toString(jumlah);
                tampilHasil.setText(angka);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tHasilActionPerformed

    private void tKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKembaliActionPerformed
        // TODO add your handling code here:
        menuUtama menu = new menuUtama(tName,tPass,tEmail);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public void show_kalkulator() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuKalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuKalkulator(tName,tPass,tEmail).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tBagi;
    private javax.swing.JButton tClear;
    private javax.swing.JButton tDelapan;
    private javax.swing.JButton tDua;
    private javax.swing.JButton tEmpat;
    private javax.swing.JButton tEnam;
    private javax.swing.JButton tHasil;
    private javax.swing.JButton tKali;
    private javax.swing.JButton tKembali;
    private javax.swing.JButton tKurang;
    private javax.swing.JButton tLima;
    private javax.swing.JButton tNol;
    private javax.swing.JButton tSatu;
    private javax.swing.JButton tSembbilan;
    private javax.swing.JButton tTambah;
    private javax.swing.JButton tTiga;
    private javax.swing.JButton tTitik;
    private javax.swing.JButton tTujuh;
    private javax.swing.JTextField tampilHasil;
    // End of variables declaration//GEN-END:variables
}
