/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.theunknowname06.hilling;

import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/**
 *
 * @author anjay
 */
public class register extends javax.swing.JFrame {
    private String tPass;
    private String tEmail;
    private String tName;
    private final String c_ram = generateVerificationCode();
    private static final String HOST = "your-host";
    private static final String PORT = "your-port";
    private static final String USERNAME = "your-email";
    private static final String PASSWORD = "your-password";
    private static String RECIPIENT_EMAIL = "";
    //for above code do not fill because this will be replace with sendEmailVerification() it self
    private static final String SUBJECT = "Email Verification";
    private static String VERIFICATION_CODE = "12345";
    /**
     * Creates new form register
     */
    public register(String n,String p,String e) {
       this.tPass = p;
        this.tName = n;
        this.tEmail = e;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        picture = new javax.swing.JPanel();
        fotonya = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        TITLE_REGISTER = new javax.swing.JPanel();
        REGISTER_TEXT = new javax.swing.JLabel();
        NAME_FORM = new javax.swing.JPanel();
        name_title = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        EMAIL_FORM = new javax.swing.JPanel();
        email_title = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        PASSWORD_FORM = new javax.swing.JPanel();
        password_title = new javax.swing.JLabel();
        show_password = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        verification_email = new javax.swing.JButton();
        VCode = new javax.swing.JPanel();
        titleCode = new javax.swing.JLabel();
        codeVerify = new javax.swing.JTextField();
        register = new javax.swing.JButton();
        account = new javax.swing.JPanel();
        titleaccount = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        exitting = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        fotonya.setIcon(new javax.swing.ImageIcon("C:\\Users\\anjay\\Downloads\\hilling\\20230610_190048_0000.png")); // NOI18N
        fotonya.setToolTipText("");

        javax.swing.GroupLayout pictureLayout = new javax.swing.GroupLayout(picture);
        picture.setLayout(pictureLayout);
        pictureLayout.setHorizontalGroup(
            pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotonya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pictureLayout.setVerticalGroup(
            pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pictureLayout.createSequentialGroup()
                .addComponent(fotonya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        menu.setBackground(new java.awt.Color(0, 255, 204));
        menu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TITLE_REGISTER.setBackground(new java.awt.Color(255, 255, 51));

        REGISTER_TEXT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        REGISTER_TEXT.setText("REGISTER PAGE");

        javax.swing.GroupLayout TITLE_REGISTERLayout = new javax.swing.GroupLayout(TITLE_REGISTER);
        TITLE_REGISTER.setLayout(TITLE_REGISTERLayout);
        TITLE_REGISTERLayout.setHorizontalGroup(
            TITLE_REGISTERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TITLE_REGISTERLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(REGISTER_TEXT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TITLE_REGISTERLayout.setVerticalGroup(
            TITLE_REGISTERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(REGISTER_TEXT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        NAME_FORM.setBackground(new java.awt.Color(153, 255, 204));

        name_title.setText("NAME:");

        name.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout NAME_FORMLayout = new javax.swing.GroupLayout(NAME_FORM);
        NAME_FORM.setLayout(NAME_FORMLayout);
        NAME_FORMLayout.setHorizontalGroup(
            NAME_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAME_FORMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        NAME_FORMLayout.setVerticalGroup(
            NAME_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NAME_FORMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NAME_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addGroup(NAME_FORMLayout.createSequentialGroup()
                        .addComponent(name_title)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        EMAIL_FORM.setBackground(new java.awt.Color(153, 255, 204));

        email_title.setText("EMAIL:");

        email.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout EMAIL_FORMLayout = new javax.swing.GroupLayout(EMAIL_FORM);
        EMAIL_FORM.setLayout(EMAIL_FORMLayout);
        EMAIL_FORMLayout.setHorizontalGroup(
            EMAIL_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EMAIL_FORMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(EMAIL_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EMAIL_FORMLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        EMAIL_FORMLayout.setVerticalGroup(
            EMAIL_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EMAIL_FORMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(EMAIL_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EMAIL_FORMLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(email)
                    .addContainerGap()))
        );

        PASSWORD_FORM.setBackground(new java.awt.Color(153, 255, 204));

        password_title.setText("PASSWORD:");

        show_password.setBackground(new java.awt.Color(153, 255, 204));
        show_password.setText("show password");
        show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_passwordActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout PASSWORD_FORMLayout = new javax.swing.GroupLayout(PASSWORD_FORM);
        PASSWORD_FORM.setLayout(PASSWORD_FORMLayout);
        PASSWORD_FORMLayout.setHorizontalGroup(
            PASSWORD_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PASSWORD_FORMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PASSWORD_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PASSWORD_FORMLayout.createSequentialGroup()
                        .addComponent(password)
                        .addContainerGap())
                    .addGroup(PASSWORD_FORMLayout.createSequentialGroup()
                        .addGroup(PASSWORD_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PASSWORD_FORMLayout.createSequentialGroup()
                                .addComponent(password_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(20, 20, 20))
                            .addComponent(show_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(234, 234, 234))))
        );
        PASSWORD_FORMLayout.setVerticalGroup(
            PASSWORD_FORMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PASSWORD_FORMLayout.createSequentialGroup()
                .addComponent(password_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        verification_email.setBackground(new java.awt.Color(153, 255, 204));
        verification_email.setText("get verification code");
        verification_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verification_emailActionPerformed(evt);
            }
        });

        VCode.setBackground(new java.awt.Color(153, 255, 204));

        titleCode.setText("PUTCODE:");

        codeVerify.setBackground(new java.awt.Color(153, 255, 204));
        codeVerify.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        register.setBackground(new java.awt.Color(0, 255, 204));
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VCodeLayout = new javax.swing.GroupLayout(VCode);
        VCode.setLayout(VCodeLayout);
        VCodeLayout.setHorizontalGroup(
            VCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(codeVerify)
                    .addGroup(VCodeLayout.createSequentialGroup()
                        .addComponent(titleCode)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VCodeLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(176, 176, 176))
        );
        VCodeLayout.setVerticalGroup(
            VCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codeVerify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        account.setBackground(new java.awt.Color(153, 255, 204));

        titleaccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        titleaccount.setText("already have account??");

        login.setBackground(new java.awt.Color(153, 255, 204));
        login.setText("LOGIN HERE");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        exitting.setBackground(new java.awt.Color(153, 255, 204));
        exitting.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        exitting.setText("EXIT");
        exitting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exittingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountLayout = new javax.swing.GroupLayout(account);
        account.setLayout(accountLayout);
        accountLayout.setHorizontalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitting, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        accountLayout.setVerticalGroup(
            accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        jLabel1.setText("<html>&copy; TheUnknownName06 </html>");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NAME_FORM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EMAIL_FORM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verification_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PASSWORD_FORM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(TITLE_REGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(TITLE_REGISTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NAME_FORM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EMAIL_FORM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PASSWORD_FORM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verification_email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(VCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33)
                .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login pg_login = new login(tName,tPass,tEmail);
        pg_login.show_login();
    }//GEN-LAST:event_loginActionPerformed

    private void exittingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exittingActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exittingActionPerformed

    private void verification_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verification_emailActionPerformed
        // TODO add your handling code here:
        String e_ram = email.getText().trim();
        if(e_ram.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter your email address.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
//        javax.swing.JOptionPane.showMessageDialog(this, e_ram, "EMAIL", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        System.out.println(e_ram);
        System.out.println(c_ram);
        boolean ret = sendVerificationEmail(e_ram, c_ram);
        if (ret) {
            javax.swing.JOptionPane.showMessageDialog(this, "Verification email sent successfully.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
           javax.swing.JOptionPane.showMessageDialog(this, "Failed to send verification email.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_verification_emailActionPerformed

    private void show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_passwordActionPerformed
        // TODO add your handling code here:
        javax.swing.JCheckBox checkBox = (javax.swing.JCheckBox) evt.getSource();
        if (checkBox.isSelected()) {
            password.setEchoChar((char) 0); // Tampilkan karakter asli
        } else {
            password.setEchoChar('\u2022'); // Gunakan karakter bintang (default)
        }
    }//GEN-LAST:event_show_passwordActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        tPass = password.getText();
        tName = name.getText();
        tEmail = email.getText();
        String token = codeVerify.getText();
        if (tName.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter your Name.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tEmail.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter your Email.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tPass.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter your password.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
         if (!token.equals(c_ram)){
            javax.swing.JOptionPane.showMessageDialog(this, "Code verification wrong!!!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
    showMessageDialog("Registration successful!", "Success", javax.swing.JOptionPane.NO_OPTION);
    this.dispose();
    login pg_login = new login(tName,tPass,tEmail);
        pg_login.show_login();
    }//GEN-LAST:event_registerActionPerformed


private void showMessageDialog(String message, String title, int messageType) {
    javax.swing.JOptionPane.showMessageDialog(null, message, title, messageType);
}

    /**
     * @param args the command line arguments
     */
    public void show_register() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register(tName,tPass,tEmail).setVisible(true);
            }
        });
    }
    
    private static String generateVerificationCode() {
    // Generate a random six-digit verification code
    Random random = new Random();
    int verificationCode = random.nextInt(900000) + 100000; // Generates a number between 100000 and 999999
    return String.valueOf(verificationCode);
    }
    
    public static boolean sendVerificationEmail(String email, String codeVerify) {
    // SMTP server properties
    RECIPIENT_EMAIL = email;
    VERIFICATION_CODE = codeVerify;
    Properties properties = new Properties();
    properties.put("mail.smtp.host", HOST);
    properties.put("mail.smtp.port", PORT);
    properties.put("mail.smtp.auth", "true");
    properties.put("mail.debug", "false"); 
    properties.put("mail.smtp.starttls.enable", "true");
    properties.put("mail.smtp.starttls.required", "true");
    properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
    properties.put("mail.smtp.starttls.enable", "true");
    properties.put("mail.smtp.socketFactory.port", "465");
    properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
    properties.put("mail.smtp.socketFactory.fallback", "false");
    properties.put("mail.smtp.ssl.enable", "true");

    // Create a session with authentication
    Authenticator authenticator = new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
            return new PasswordAuthentication(USERNAME, PASSWORD);
        }
    };
    Session session = Session.getInstance(properties, authenticator);

    try {
        // Create an email message
        Message message = new MimeMessage(session);
        message.setFrom(new InternetAddress(USERNAME));
        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(RECIPIENT_EMAIL));
        message.setSubject(SUBJECT);
        message.setText("Please use the following verification code: " + VERIFICATION_CODE);

        // Send the email
        Transport.send(message);
        return true;
    } catch (MessagingException e) {
        return false;
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EMAIL_FORM;
    private javax.swing.JPanel NAME_FORM;
    private javax.swing.JPanel PASSWORD_FORM;
    private javax.swing.JLabel REGISTER_TEXT;
    private javax.swing.JPanel TITLE_REGISTER;
    private javax.swing.JPanel VCode;
    private javax.swing.JPanel account;
    private javax.swing.JTextField codeVerify;
    private javax.swing.JTextField email;
    private javax.swing.JLabel email_title;
    private javax.swing.JButton exitting;
    private javax.swing.JLabel fotonya;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField name;
    private javax.swing.JLabel name_title;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel password_title;
    private javax.swing.JPanel picture;
    private javax.swing.JButton register;
    private javax.swing.JCheckBox show_password;
    private javax.swing.JLabel titleCode;
    private javax.swing.JLabel titleaccount;
    private javax.swing.JButton verification_email;
    // End of variables declaration//GEN-END:variables
}
